### ISSUE TITLE
List Best Practices separately

### ISSUE THREAD

**Issue by fsundermeyer** [doc-suse-com/site#10]
* SUSE Best Practices is listed first in the product list, although it is not a product
* we need to have a product filter for the best practices in the select version box

**Comment by chabowski** [comment]
A while ago, Stefan and I discussed the option of real tabs on doc serv. 
Currently, everything is listed as "Product Documentation". 

- But the Best Practices are not really proper product documentation. They are "Solution Documentation" or "Best Practices".
- In future, we might even add "Technical Alliances Documentation" (or "Hardware and Software specific Documentation" or whatever) to the page. 

Thus - if possible - I would like to have "Tabs" where you can choose from, similar to here: 
https://www.redhat.com/en/technologies
You can click on "Cloud", "Infrastructure", "Integration", etc.

And for documentation, we could have: "Product Documentation", "Solution Documentation", "Technical Alliances Documents", etc - and even add more if needed.

**Comment by ghost** [comment]
This has been fixed for a while (I don't have sufficient rights to close this anymore though).

**Comment by taroth21** [comment]
@sknorr : Thanks for the update, closing now.
